# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Add job for your FastAPI app if it exposes metrics
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['app:7010']
